services:
  web:
    build:
      context: .
      dockerfile: ./compose/fastapi/Dockerfile
    image: todo-web:latest
    container_name: todo-web
    # command refers to area in container where the start script is located, and
    # has nothing to do with what is in the home directory of the project. It is just a command to run when the container starts.
    command: /start
    volumes:
      - .:/app
    ports:
      - "8010:8000"
    env_file:
      - .env/.env.local
    restart: unless-stopped
    depends_on:
      - redis
      - db

  db:
    image: postgres:16-alpine
    container_name: todo-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env/.env.local
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  redis:
    image: redis:latest
    container_name: todo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/fastapi/Dockerfile
    image: todo-celery-worker:latest
    container_name: todo-celery-worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - .env/.env.local
    restart: unless-stopped
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/fastapi/Dockerfile
    image: todo-celery-beat:latest
    container_name: todo-celery-beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - .env/.env.local
    restart: unless-stopped
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./compose/fastapi/Dockerfile
    image: todo-flower:latest
    container_name: todo-flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - .env/.env.local
    restart: unless-stopped
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db

volumes:
  redis-data:
  postgres-data:
